m

diff --git a/trunk/.JS/bin/VMSTAT b/trunk/.JS/bin/VMSTAT
--- a/trunk/.JS/bin/VMSTAT
+++ b/trunk/.JS/bin/VMSTAT
@@ -20,16 +20,19 @@ while [ $# -gt 0 ]; do
             usage; exit 0;;
         --ticklen)
             shift; TICKLEN=$1;; #debug only, if specified must before DURATION to take effect
-        [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
+        [0-9]|[0-9]*[0-9])
             DELAY=$1;;
-        [0-9][smht]|[0-9][0-9][smht]|[0-9][0-9][0-9][smht]|[0-9][0-9][0-9][0-9][smht])
+        [0-9][smht]|[0-9]*[0-9][smht])
             NUM=`echo "$1" | sed -e 's/.$//'`
             case "$1" in
                 *s) DURATION=$NUM;;
                 *m) DURATION=`expr $NUM '*' 60`;;
                 *h) DURATION=`expr $NUM '*' 3600`;;
                 *t) DURATION=`expr $NUM '*' $TICKLEN`;;
-            esac;;
+            esac
+            expr "$DURATION" "*" "1" >/dev/null 2>&1 || { echo 1>&2 "($PROGRAM)Error: Invalid option '$1'"; usage; exit 1;}
+            ;;
+
         -v)
             VERBOSE=1;;
         *)
diff --git a/trunk/HSIM/bin/hs b/trunk/HSIM/bin/hs
--- a/trunk/HSIM/bin/hs
+++ b/trunk/HSIM/bin/hs
@@ -38,12 +38,13 @@ DO_HSIM()
         AJC[0-9][0-9][0-9][0-9][0-9][0-9])
             TEST_BASE=$HSIM_HOME/AJC
             ;;
-        IS[0-9][0-9][0-9][0-9][0-9][0-9])
+        ISV[0-9][0-9][0-9][0-9][0-9][0-9])
             TEST_BASE=$HSIM_HOME/iServer
             ;;
         *)
-            echo 1>&2 "($PROGRAM)Error: Invalid SERVER_TYPE '$SERVER_TYPE'"
-            exit 1
+            TEST_BASE=$HSIM_HOME/iServer
+#            echo 1>&2 "($PROGRAM)Error: Invalid SERVER_TYPE '$SERVER_TYPE'"
+#            exit 1
             ;;
     esac
     TESTCASE=$TEST_BASE/$ARG3/$ARG4.sim
@@ -60,7 +61,7 @@ DO_HSIM()
         "")
             LOG=sanity.log
             EVAL hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE 1 1i -V "|" tee $LOG | grep ' | '
-            ERRCNT=`egrep -c ' \| .*error' $LOG`
+            ERRCNT=`grep ' | ' $LOG | egrep -c -v ' \| OK'`
 
             echo | tee -a $LOG
             echo "##########################!CMD:[ grep ' | ' $LOG ]########################" >> $LOG
