create *.sim automatically in hs

diff --git a/trunk/HSIM/bin/hs b/trunk/HSIM/bin/hs
--- a/trunk/HSIM/bin/hs
+++ b/trunk/HSIM/bin/hs
@@ -53,7 +53,13 @@ DO_HSIM()
             ;;
     esac
     TESTCASE=$TEST_BASE/$ARG3/$ARG4.sim
-    [ ! -f "$TESTCASE" ] && { echo 1>&2 "($PROGRAM)Error: TESTCASE '$TESTCASE' doesn't exist"; exit 1;}
+    if [ ! -f "$TESTCASE" ]; then
+        if [ -f "$TEST_BASE/$ARG3/__template__.sim" ]; then
+            (cd "$TEST_BASE/$ARG3" && EVAL cp_sims __template__.sim $ARG4)
+        else
+            echo 1>&2 "($PROGRAM)Error: TESTCASE '$TESTCASE' doesn't exist"; exit 1
+        fi
+    fi
 
     case "$ARG5" in
         *[0-9].*[0-9][smhti]*)
