3

diff --git a/trunk/HSIM/bin/hs b/trunk/HSIM/bin/hs
--- a/trunk/HSIM/bin/hs
+++ b/trunk/HSIM/bin/hs
@@ -18,53 +18,53 @@ BASE64_DECODE()
         -e 's/bA[a-zA-Z0-9/+=]\{254\}/BASE64[256]/g'
 }
 
-DO_HSIM()
+ARGS_START=`hsPrintf "%S %H $HSIM_HOME/%T %N %L"` || exit 1
+
+ht()
 {
-    ARGS_START=`hsPrintf "%S %H $HSIM_HOME/%T %N %L"` || exit 1
+    LOG=`NEWFILE ht.log`
+    case "$ARGS_START" in
+        *[0-9]i)
+            ARGS_TEST="$ARGS_START -V";;
+        *)
+            ARGS_TEST=`echo $ARGS_START | awk '{print $1, $2, $3, "1 1i -V"}'`;;
+    esac
 
-    if [ "$PROGRAM" = "ht" -o "$PROGRAM" = "hts" ]; then
-        LOG=`NEWFILE ht.log`
-        case "$ARGS_START" in
-            *[0-9]i)
-                ARGS_TEST="$ARGS_START -V";;
-            *)
-                ARGS_TEST=`echo $ARGS_START | awk '{print $1, $2, $3, "1 1i -V"}'`;;
-        esac
-        for i in 1 2; do
-            _EVAL hsRun $ARGS_TEST "|" tee $LOG | egrep --line-buffered '( \| )|(^\[.*\]$)' | BASE64_DECODE
-            ERRCNT=`grep ' | ' $LOG | egrep -c -v ' \| OK'`
+    _EVAL hsRun $ARGS_TEST "|" tee $LOG | egrep --line-buffered '( \| )|(^\[.*\]$)' | BASE64_DECODE
+    ERRCNT=`grep ' | ' $LOG | egrep -c -v ' \| OK'`
 
-            echo | tee -a $LOG
-            echo "##########################!CMD:[ grep ' | ' $LOG ]########################" >> $LOG
-            grep ' | ' $LOG | grep -v 'grep' | BASE64_DECODE >> $LOG
+    echo | tee -a $LOG
+    echo "##########################!CMD:[ grep ' | ' $LOG ]########################" >> $LOG
+    grep ' | ' $LOG | grep -v 'grep' | BASE64_DECODE >> $LOG
 
-            if [ $ERRCNT -eq 0 -a `grep -c '| OK' $LOG` -gt 0 ]; then
-                echo "($PROGRAM)Note: Hsim Test PASS. Verbose output is saved in $LOG"
-                echo
-                break
-            else
-                echo "($PROGRAM)Error: Hsim Test FAIL. Verbose output is saved in $LOG"
-                echo
-                if [ $i -eq 2 ]; then #Check for 2 times
-                    ERRSUM=`expr $ERRSUM '+' $ERRCNT`
-                    return #ht failed, and thus won't hs anymore.
-                fi
-            fi
-        done
+    if [ $ERRCNT -eq 0 -a `grep -c '| OK' $LOG` -gt 0 ]; then
+        echo "($PROGRAM)Note: Hsim Test PASS. Verbose output is saved in $LOG"
+        echo
+        return 0
+    else
+        echo "($PROGRAM)Error: Hsim Test FAIL. Verbose output is saved in $LOG"
+        echo
+        return 1
     fi
+}
 
-    if [ "$PROGRAM" = "hs" -o "$PROGRAM" = "hts" ]; then
-        case "$ARGS_START" in
-            *[0-9][smhti])
-                    LOG=`NEWFILE hs.log`
-                    echo "#!CMD:[ hsRun $ARGS_START --job hs.perfmon ]" > $LOG
-                    _EVAL hsRun $ARGS_START --job hs.perfmon "|" tee -a $LOG
-                    ;;
-            *)
-                    echo 1>&2 "Error: Invalid hsRun arguments '$ARGS_START'"
-                    ;;
-        esac
-    fi
+hs()
+{
+    case "$ARGS_START" in
+        *[0-9][smhtTi])
+                LOG=`NEWFILE hs.log`
+                echo "#!CMD:[ hsRun $ARGS_START --job hs.perfmon ]" > $LOG
+                _EVAL hsRun $ARGS_START --job hs.perfmon "|" tee -a $LOG
+                ;;
+        *)
+                echo 1>&2 "Error: Invalid hsRun arguments '$ARGS_START'"
+                ;;
+    esac
+}
+
+hts()
+{
+    ht || ht && hs #Test twice, and start run if any test passed.
 }
 
 while [ $# -gt 0 ]; do
@@ -75,13 +75,9 @@ while [ $# -gt 0 ]; do
 done
 [ -z "$DIRS" ] && DIRS="$PWD"
 
-ERRSUM=0
-
 ORIG_PWD="$PWD"
 for DIR in $DIRS; do
     echo
-    _EVAL cd "$DIR" && DO_HSIM || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
+    _EVAL cd "$DIR" && { $PROGRAM; true;} || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
     cd "$ORIG_PWD"
 done
-
-exit $ERRSUM
diff --git a/trunk/HSIM/bin/hsTraverse b/trunk/HSIM/bin/hsTraverse
--- a/trunk/HSIM/bin/hsTraverse
+++ b/trunk/HSIM/bin/hsTraverse
@@ -54,7 +54,7 @@ for ROUND in `seq 1 $REPEAT`; do
     [ $REPEAT -gt 1 ] && echo "[ROUND: $ROUND]"
     for ROOT in $ROOTS; do
         for DIR in `find $ROOT -name "[0-9]*\.*[0-9][tT]" -type d`; do
-            EVAL cd "$DIR" && EVAL "hts; sleep $DELAY" || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
+            EVAL cd "$DIR" && { EVAL hts; EVAL sleep $DELAY;} || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
         done
         echo
     done
