Repeat

diff --git a/trunk/HSIM/bin/hs b/trunk/HSIM/bin/hs
--- a/trunk/HSIM/bin/hs
+++ b/trunk/HSIM/bin/hs
@@ -30,7 +30,7 @@ ERRSUM=0
 DO_HSIM()
 {
     SERVER_ADDR=`pwd | awk -F@ '{print $NF}' | awk -F/ '{print $1}'`
-    SERVER_TYPE=`pwd | awk -F@ '{print $NF}' | awk -F/ '{print $2}' | sed -e 's/\./ /g'`
+    SERVER_TYPE=`pwd | awk -F@ '{print $NF}' | awk -F/ '{print $2}'`
     ARG3=`pwd | awk -F@ '{print $NF}' | awk -F/ '{print $3}'`
     ARG4=`pwd | awk -F@ '{print $NF}' | awk -F/ '{print $4}'`
 
@@ -54,12 +54,12 @@ DO_HSIM()
         *[0-9].*[0-9][smhti])
             CLIENT_NUM_DURATION=`echo "$ARG5" | sed -e 's/\./ /g'`
             LOG=`NEWFILE $PROGRAM.log`
-            echo "#!CMD:[ hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE $CLIENT_NUM_DURATION --job hs.perfmon ]" > $LOG
-            EVAL hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE $CLIENT_NUM_DURATION --job hs.perfmon "|" tee -a $LOG
+            echo "#!CMD:[ hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE $CLIENT_NUM_DURATION --job hs.perfmon $OPTS]" > $LOG
+            EVAL hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE $CLIENT_NUM_DURATION --job hs.perfmon $OPTS "|" tee -a $LOG
             ;;
         "")
             LOG=sanity.log
-            EVAL hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE 1 1i -V "|" tee $LOG | grep ' | '
+            EVAL hsRun $SERVER_TYPE $SERVER_ADDR $TESTCASE 1 1i -V $AJCS "|" tee $LOG | egrep '( \| )|(^\[.*\]$)'
             ERRCNT=`grep ' | ' $LOG | egrep -c -v ' \| OK'`
 
             echo | tee -a $LOG
@@ -81,15 +81,21 @@ DO_HSIM()
     esac
 }
 
-if [ $# -eq 0 ]; then
-    DO_HSIM
-else
-    ORIG_PWD="$PWD"
-    for DIR do
-        echo
-        EVAL cd "$DIR" && DO_HSIM || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
-        cd "$ORIG_PWD"
-    done
-fi
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -R) shift; OPTS="$OPTS -R $1";;
+        AJC*) AJCS="$AJCS $1"; OPTS="$OPTS $1";;
+        *) DIRS="$DIRS $1";;
+    esac
+    shift
+done
+[ -z "$DIRS" ] && DIRS="$PWD"
+
+ORIG_PWD="$PWD"
+for DIR in $DIRS; do
+    echo
+    EVAL cd "$DIR" && DO_HSIM || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
+    cd "$ORIG_PWD"
+done
 
 exit $ERRSUM
