0

diff --git a/trunk/HSIM/bin/hsInit b/trunk/HSIM/bin/hsInit
--- a/trunk/HSIM/bin/hsInit
+++ b/trunk/HSIM/bin/hsInit
@@ -3,14 +3,20 @@
 PROGRAM=`basename $0`
 usage()
 {
-    echo 1>&2 "Usage: $PROGRAM YYMMDD HOST"
-    echo 1>&2 "       $PROGRAM 121207 sha-perf"
+    echo 1>&2 "Usage: $PROGRAM YYMMDD HOST [-f]"
+    echo 1>&2 "       $PROGRAM 121207 sha-perf     --Initialize new directory 121207@sha-perf"
+    echo 1>&2 "       $PROGRAM 121207 sha-perf -f  --Reinitialize directory 121207@sha-perf"
 }
 
 while [ $# -gt 0 ]; do
     case "$1" in
         [0-9][0-9][0-9][0-9][0-9][0-9]) YYMMDD="$1";;
-        [a-zA-z]*) HOST="$1";;
+        [a-zA-Z]*) HOST="$1";;
+        [0-9][0-9][0-9][0-9][0-9][0-9]@[a-zA-Z]*)
+            YYMMDD=`echo $1 | sed -e 's/@.*$//'`
+            HOST=`echo $1 | sed -e 's/^.*@//' -e 's@/*$@@'`
+            ;;
+        -f) OVERRIDE=1;;
         --help) usage; exit 0;;
         *) echo 1>&2 "Error: Invalid option '$1'"; usage; exit 1;;
     esac
@@ -19,7 +25,7 @@ done
 
 [ -n "$YYMMDD" ] || { echo 1>&2 "Error: YYMMDD is not set!"; usage; exit 2;}
 [ -n "$HOST" ] || { echo 1>&2 "Error: HOST is not set!"; usage; exit 2;}
-[ -d "$YYMMDD@$HOST" ] && { echo 1>&2 "Error: '$YYMMDD@$HOST' already exists. Remove it if need reinit."; exit 3;}
+[ -d "$YYMMDD@$HOST" -a -z "$OVERRIDE" ] && { echo 1>&2 "Error: '$YYMMDD@$HOST' already exists. Remove it first, or use option '-f' if need reinit."; exit 3;}
 
 mkdir -p -v	$YYMMDD@$HOST/AJC$YYMMDD/SV/10.CrosstabSampleRevenue#html/{1,6}.6t
 mkdir -p -v	$YYMMDD@$HOST/AJC$YYMMDD/SV/11.CustomerDashboard#html/{1,6}.6t
@@ -87,5 +93,5 @@ mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/B1_JOIN_x{1,100}/{1,14}.6t
 #mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/C2_FILTER_Many_x{1,100}/{1,14}.6t
 #mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/C3_FILTER_Some_x{1,100}/{1,14}.6t
 #mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/C4_FILTER_Some_NoSummary_x{1,100}/{1,14}.6t
-mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/M1_xTab_by_INT_STRING_x{1,100}/{1,14}.6t
-mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/M1_xTab_by_STRING_YEAR_x{1,100}/{1,14}.6t
+mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/M1_Simple_xTab_x{1,100}/{1,14}.6t
+mkdir -p -v	$YYMMDD@$HOST/iServer/LDS/M2_Nation_Year_xTab_x{1,100}/{1,14}.6t
