.

diff --git a/trunk/HSIM/bin/hsTraverse b/trunk/HSIM/bin/hsTraverse
--- a/trunk/HSIM/bin/hsTraverse
+++ b/trunk/HSIM/bin/hsTraverse
@@ -34,8 +34,8 @@ DO_TRAVERSE()
         pwd | awk '{print "#!CMD:[ cd " $0 " ]"}'
         case `pwd | awk -F@ '{print $NF}' | awk -F/ '{print NF}'` in
             1|2|3) DO_TRAVERSE */;;
-            4) EVAL "hs || hs && hs [0-9]*.*[0-9][smht]";; #sanity (try twice) && execute
-            5) EVAL "hs";;
+            4) EVAL "hs || hs && hs [0-9]*.*[0-9][smht]$OPTS";; #sanity (try twice) && execute
+            5) EVAL "hs$OPTS";;
             *) echo 1>&2 "Error: Invalid root directory '$PWD' to traverse"; return 1;;
         esac
         cd $OLD_PWD
@@ -49,3 +49,21 @@ else
     DO_TRAVERSE "$@"
 fi 2>&1 | tee `NEWFILE $PROGRAM.log`
 
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -R) shift; OPTS="  -R $1";;
+        *) DIRS="$DIRS $1";;
+    esac
+    shift
+done
+[ -z "$DIRS" ] && DIRS="$PWD"
+
+ORIG_PWD="$PWD"
+for DIR in $DIRS; do
+    echo
+    EVAL cd "$DIR" && DO_HSIM || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
+    cd "$ORIG_PWD"
+done
+
+exit $ERRSUM
