1

diff --git a/trunk/HSIM/bin/hsTraverse b/trunk/HSIM/bin/hsTraverse
--- a/trunk/HSIM/bin/hsTraverse
+++ b/trunk/HSIM/bin/hsTraverse
@@ -35,53 +35,28 @@ NEWFILE()
 }
 ##################### .JS/bin/_SH_UTIL_FUNCTIONS <END> #########################
 
-DO_TRAVERSE()
-{
-    pwd | awk '{print "#!CMD:[ cd " $0 " ]"}'
-    case `pwd | awk -F@ '{print $NF}' | awk -F/ '{print NF}'` in
-        1|2) $PROGRAM */ $OPTS;;
-        3) EVAL "ht || ht && hs *[0-9].*[0-9][tT] $OPTS";; #sanity (try twice) && execute
-        4) EVAL "hs $OPTS";;
-        *) echo 1>&2 "Error: Invalid root directory '$PWD' to traverse"; return 1;;
-    esac
-    echo
-}
-
+REPEAT=1
+DELAY=0
 while [ $# -gt 0 ]; do
     case "$1" in
         --help) usage; exit 0;;
-        -R) shift; OPTS="$OPTS -R $1";;
-        -D) shift; OPTS="$OPTS -D $1";;
-        -t) shift; NO_EVAL=TRUE;;
+        -R) shift; REPEAT=$1;;
+        -D) shift; DELAY=$1;;
+        -t) NO_EVAL=TRUE;;
         -*) usage; exit 1;;
-        *) DIRS="$DIRS $1";;
+        *) ROOTS="$ROOTS `( cd $1 && pwd )`";;
     esac
     shift
 done
-[ -z "$DIRS" ] && DIRS="$PWD"
+[ -z "$ROOTS" ] && ROOTS="$PWD"
 
-MAIN()
-{
-    ORIG_PWD="$PWD"
-    for DIR in $DIRS; do
+for ROUND in `seq 1 $REPEAT`; do
+    [ $REPEAT -gt 1 ] && echo "[ROUND: $ROUND]"
+    for ROOT in $ROOTS; do
+        for DIR in `find $ROOT -name "[0-9]*\.*[0-9][tT]" -type d`; do
+            EVAL cd "$DIR" && EVAL "hts; sleep $DELAY" || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
+        done
         echo
-        cd "$DIR" && DO_TRAVERSE || echo 1>&2 "($PROGRAM)Error: Failed to enter directory '$DIR'"
-        cd "$ORIG_PWD"
     done
-}
-
-if [ -z "$LOG4hsTraverse" ]; then
-    if [ -z "$OPTS" ]; then
-        LOG4hsTraverse=`NEWFILE $PROGRAM.log`
-    else
-        LOG4hsTraverse=`echo $PROGRAM.$OPTS.log | sed -e 's/ //g'`
-        LOG4hsTraverse=`NEWFILE $LOG4hsTraverse`
-    fi
-    export LOG4hsTraverse
-
-    MAIN | tee -a $LOG4hsTraverse
-else
-    MAIN
-fi
-
-exit $ERRSUM
+    [ $REPEAT -gt 1 ] && echo
+done
